-- AlterTable
ALTER TABLE `UserVolunteer` ADD COLUMN `gender` ENUM('MALE', 'FEMALE') NOT NULL DEFAULT 'MALE',
    ADD COLUMN `role` ENUM('POLLING_AGENT', 'BLOGGING_TEAM', 'VOTER') NOT NULL DEFAULT 'POLLING_AGENT';
