-- AlterTable
ALTER TABLE `UserVolunteer` ADD COLUMN `fullName` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `pollingStation` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `ward` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `firstName` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `lastName` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `email` VARCHAR(191) NOT NULL DEFAULT '';
